name: 'todo_redarx'
version: 0.1
description: A todo app based on Redarx State management
author: Erick G. <erick@rxlabz.com>

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  redarx:
    #path: /Users/Me/projects/tools/redarx
    git:
      url: git://github.com/rxlabz/redarx
      ref: v0.2.0+1

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'

transformers:
- dart_to_js_script_rewriter
